### ISSUE TITLE
Error code  E_INVALIDARG (0x80070057) upon import of VM

### ISSUE THREAD

**Issue by haidi-ustc** [marvel-nccr/quantum-mobile#116] opened 2020-05-10 04:17 UTC
Hi, recently when i try to import Quantum Mobile 20.03.1.ova using 6.1.4 virtualbox, i get the error E_INVALIDARG (0x80070057).  Then i try to change the version of virtualbox, but it still doesn't work, would you please give me some suggestion

**Comment by ltalirz** [comment] 2020-05-10 20:24
Hi @haidi-ustc , thanks for reporting this issue. We've had another report of this error code on the AiiDA mailing list (+ via Stefaan Cottenier).

I've put a link concerning the issue in the FAQ https://github.com/marvel-nccr/quantum-mobile/wiki/Frequently-Asked-Questions#virtualbox-installationstartup-issues
but the issue of lack of disk space is more of a guess from my side, based on what I've read in virtualbox forums, since I'm not able to reproduce the issue myself (I just tested importing the VM).

Some questions from my side:
* What is your hardware (including RAM + cores)?
* What is your operating system (including version)?
* When exactly does the error occur and is there any further information provided by VirtualBox?

There are a couple of recent hits for the error code in the virtualbox forums; you're welcome to try some of the suggestions provided there and let me know if they solve your issue
https://www.google.com/search?q=E_INVALIDARG+site:forums.virtualbox.org&sxsrf=ALeKk01_zian4gGCGoLp413ry324_W1dVQ:1589142159026&source=lnt&tbs=qdr:y&sa=X&ved=2ahUKEwjfnovvj6rpAhXnwcQBHWUpC6MQpwV6BAgMECE&biw=1728&bih=1306

**Comment by haidi-ustc** [comment] 2020-05-12 09:00
@ltalirz Thank you for your help, i try to solve it , but i seems diffcult to process. It's not a hardware problem, currently i have no idea how to process. I plan to install the aiida via an ab inito way

**Comment by ltalirz** [comment] 2020-10-04 16:18
Stefaan Cottenier reports that in one case, a student got this error with [QM v20.06.1](https://github.com/marvel-nccr/quantum-mobile/releases/tag/20.06.1) but then was able to successfully import [QM v20.06.1a1](https://github.com/marvel-nccr/quantum-mobile/releases/tag/20.06.1a1)

I have no idea what could have caused this - both releases are of similar size (9.9GB vs 9.5GB unpacked) and, I guess, with a similar build process @chrisjsewell @borellim

**Comment by lmacenul** [comment] 2020-10-04 18:04
Hello there; I am one of Stephen Cottenier's students who ran into the aforementioned error. I ran into it with both QM v20.06.1 AND QM v20.06.1a1. The error only went away when I took the time to make space on my hard disk. I report my specs:

1) Operating System - macOS 10.15.2
2) File system - APFS
3) Virtualbox version - 6.1.14 r140239

**Comment by summerrtime** [comment] 2020-10-04 18:06
Hi,

I'm the other student facing this issue in QM v20.06.1 with the following details:

- Windows 10
- NTFS, 298 GB 
- Virtualbox 6.1.14

But I could import QM v20.06.1a1 without any error.

Thank you for helping.

**Comment by ltalirz** [comment] 2020-10-07 08:17
Thanks @lmacenul and @summerrtime for your reports.

From the reports and our experience so far it seems that on Macos/Linux machines the error may indeed indicate a lack of free space for extracting the image, but on Windows it may also have a different cause.

I really wonder though how this error can go away by switching from v20.06.1 to v20.06.1a1... 
I'll try it once on a windows machine of mine when I have time, in the meanwhile all ideas are welcome

**Comment by ltalirz** [comment] 2021-08-02 09:31
I remember checking whether QM ran on VirtualBox under Windows and it seemed to work fine.
I'm closing this for now - feel free to reopen if the issue resurfaces.

**Closed by ltalirz** 2021-08-02 09:31 UTC
Labels: bug, virtualbox
